version: "3.9"

networks:
  lego_network:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
    networks:
      - lego_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - lego_network
